### ISSUE TITLE
Migration checklist

### ISSUE THREAD

**Issue by amadeuspzs** [amadeuspzs/homeassistant-config#1]
- [x] Setup influxdb
- [x] Backup influxdb
- [x] Notebook connecting to Influxdb
- ~[ ] Fix https://github.com/home-assistant/core/issues/85262~
- [x] Move over MQTT sensors
- [x] Move over climate
- [x] Move over automations
- [x] Move over custom power scripts
- [x] Check templates for batteries
- [x] Reimplement UI
- [x] Check native Energy functionality and match units
- [x] Start on system boot

**Comment by amadeuspzs** [comment]
https://community.home-assistant.io/t/autostart-using-systemd/199497
